const http=require('http'); const crypto=require('crypto'); const zlib=require('zlib'); const fs=require('fs'); const cp=require('child_process');
const O='https://www.southcarolinaprobate.net', T=O+'/search/ViewImage.aspx?id=61fd5200-b215-49a2-ba59-0ca38cc3aa3e'; let result={status:'starting'};
function pick(s,r){const m=s.match(r);return m?m[1]:null;} function cookies(h){const a=h.getSetCookie?h.getSetCookie():[];return a.map(x=>x.split(';')[0]).join('; ');} function decxml(s){return s.replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d)=>String.fromCodePoint(+d)).replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');}
function keyFor(name,password){const k=Buffer.alloc(16);for(let i=0;i<16;i++){let v=i;if(i<password.length)v|=password.charCodeAt(i);const g=name.length+i-16;if(g>=0)v|=name.charCodeAt(g);k[i]=v&255;}return k;}
function partsFromEncryptedZip(file,password){const eocd=file.length-22;const cdLoc=file.readUInt32LE(eocd+16), cdSize=file.readUInt32LE(eocd+12);let pos=cdLoc;const out=[];while(pos<cdLoc+cdSize){if(file.readUInt32LE(pos)!==0x02014b50)break;const method=file.readUInt16LE(pos+10), comp=file.readUInt32LE(pos+20), uncomp=file.readUInt32LE(pos+24), fnl=file.readUInt16LE(pos+28), exl=file.readUInt16LE(pos+30), coml=file.readUInt16LE(pos+32), local=file.readUInt32LE(pos+42);const name=file.subarray(pos+46,pos+46+fnl).toString('utf8');const lfn=file.readUInt16LE(local+26), lex=file.readUInt16LE(local+28), start=local+30+lfn+lex;const enc=file.subarray(start,start+comp);let raw=enc;if(enc.length>=16 && enc.length%16===0){const iv=enc.subarray(0,16), ct=enc.subarray(16);const d=crypto.createDecipheriv('aes-128-cbc',keyFor(name,password),iv);d.setAutoPadding(false);raw=Buffer.concat([d.update(ct),d.final()]);}let data;try{data=method===8?zlib.inflateRawSync(raw):Buffer.from(raw);}catch(e){data=null;}out.push({name,method,comp,uncomp,data,error:data?null:'inflate failed'});pos+=46+fnl+exl+coml;}return out;}
async function main(){try{const common={'user-agent':'Mozilla/5.0 Chrome/140 Safari/537.36','accept-language':'en-US,en;q=0.9'};const p=await fetch(T,{headers:common});const body=await p.text(),cookie=cookies(p.headers);const c={stateId:pick(body,/stateId:\s*\\?"([^"\\]+)\\?"/),handlerUrl:pick(body,/handlerUrl:\s*\\?"([^"\\]+)\\?"/),cacheInfoKey:pick(body,/cacheInfoKey:\s*\\?"([^"\\]+)\\?"/)};const H=O+c.handlerUrl,headers={...common,referer:T,cookie,accept:'*/*'};const prep=await fetch(H+'/PrepareDocument',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({cacheInfoKey:c.cacheInfoKey,stateId:c.stateId})});console.log('PREP',prep.status,await prep.text());const q=new URLSearchParams({cacheInfoKey:c.cacheInfoKey,stateId:c.stateId});const r=await fetch(H+'/DownloadDocument?'+q.toString(),{headers});const xpz=Buffer.from(await r.arrayBuffer());const password=c.cacheInfoKey.split('/')[0].replace(/\.[^.]*$/,'');console.log('XPZ',xpz.length,'PASSWORD',password);const parts=partsFromEncryptedZip(xpz,password);console.log('PART_SUMMARY_BEGIN');console.log(JSON.stringify(parts.map(x=>({name:x.name,method:x.method,comp:x.comp,uncomp:x.uncomp,ok:!!x.data,length:x.data?.length||0,error:x.error})),null,2));console.log('PART_SUMMARY_END');
 const pageTexts=[];for(const p of parts.filter(x=>/^Pages\/\d+\.xaml$/i.test(x.name)&&x.data).sort((a,b)=>parseInt(a.name.match(/\d+/)[0])-parseInt(b.name.match(/\d+/)[0]))){const s=p.data.toString('utf8');const runs=[...s.matchAll(/UnicodeString=["']([^"']*)["']/g)].map(m=>decxml(m[1]));pageTexts.push({page:parseInt(p.name.match(/\d+/)[0]),runs,text:runs.join(' ').replace(/\s+/g,' ').trim(),xaml:s.slice(0,5000)});}console.log('PAGE_TEXT_BEGIN');console.log(JSON.stringify(pageTexts,null,2));console.log('PAGE_TEXT_END');
 const structs=[];for(const p of parts.filter(x=>/^Struct\/\d+\.xml$/i.test(x.name)&&x.data)){const s=p.data.toString('utf8');structs.push({name:p.name,text:s.slice(0,20000)});}console.log('STRUCTS_BEGIN');console.log(JSON.stringify(structs,null,2));console.log('STRUCTS_END');
 let tess=false;try{cp.execFileSync('tesseract',['--version'],{stdio:'ignore'});tess=true;}catch{}console.log('TESSERACT_AVAILABLE',tess);const ocr=[];if(tess){for(const p of parts.filter(x=>/^Images\/\d+\.jpg$/i.test(x.name)&&x.data).sort((a,b)=>parseInt(a.name.match(/\d+/)[0])-parseInt(b.name.match(/\d+/)[0]))){const f='/tmp/'+p.name.replace('/','_');fs.writeFileSync(f,p.data);let text='';try{text=cp.execFileSync('tesseract',[f,'stdout','--psm','6'],{encoding:'utf8',maxBuffer:20*1024*1024});}catch(e){text=String(e.stdout||'');}ocr.push({image:p.name,text:text.trim()});}console.log('OCR_BEGIN');console.log(JSON.stringify(ocr,null,2));console.log('OCR_END');}
 result={status:'done',config:c,password,pageTexts,structs,ocr,parts:parts.map(x=>({name:x.name,ok:!!x.data,length:x.data?.length||0}))};}catch(e){result={status:'error',error:String(e&&e.stack||e)};console.error('FATAL',result);}}
main();http.createServer((q,s)=>{s.writeHead(200,{'content-type':'application/json'});s.end(JSON.stringify(result));}).listen(process.env.PORT||10000,'0.0.0.0',()=>console.log('listening'));
