const http=require('http');const crypto=require('crypto');const zlib=require('zlib');const cp=require('child_process');
const O='https://www.southcarolinaprobate.net',T=O+'/search/ViewImage.aspx?id=61fd5200-b215-49a2-ba59-0ca38cc3aa3e';let result={status:'starting'};
function pick(s,r){const m=s.match(r);return m?m[1]:null;}function cookies(h){const a=h.getSetCookie?h.getSetCookie():[];return a.map(x=>x.split(';')[0]).join('; ');}function keyFor(name,password){const k=Buffer.alloc(16);for(let i=0;i<16;i++){let v=i;if(i<password.length)v|=password.charCodeAt(i);const g=name.length+i-16;if(g>=0)v|=name.charCodeAt(g);k[i]=v&255;}return k;}
function decryptZip(file,password){let e=file.length-22;while(e>=0&&file.readUInt32LE(e)!==0x06054b50)e--;if(e<0)throw new Error('EOCD not found');const cd=file.readUInt32LE(e+16),size=file.readUInt32LE(e+12);let p=cd;const out=[];while(p<cd+size){if(file.readUInt32LE(p)!==0x02014b50)break;const method=file.readUInt16LE(p+10),comp=file.readUInt32LE(p+20),uncomp=file.readUInt32LE(p+24),fnl=file.readUInt16LE(p+28),exl=file.readUInt16LE(p+30),coml=file.readUInt16LE(p+32),local=file.readUInt32LE(p+42);const name=file.subarray(p+46,p+46+fnl).toString('utf8'),lfn=file.readUInt16LE(local+26),lex=file.readUInt16LE(local+28),start=local+30+lfn+lex;const enc=file.subarray(start,start+comp);let raw=enc;if(enc.length>=16&&enc.length%16===0){const d=crypto.createDecipheriv('aes-128-cbc',keyFor(name,password),enc.subarray(0,16));d.setAutoPadding(false);raw=Buffer.concat([d.update(enc.subarray(16)),d.final()]);}let data=null;try{data=method===8?zlib.inflateRawSync(raw):Buffer.from(raw);}catch{}out.push({name,uncomp,data});p+=46+fnl+exl+coml;}return out;}
async function main(){try{const common={'user-agent':'Mozilla/5.0 Chrome/140 Safari/537.36','accept-language':'en-US,en;q=0.9'};const pg=await fetch(T,{headers:common});const html=await pg.text(),cookie=cookies(pg.headers);const c={stateId:pick(html,/stateId:\s*\\?"([^"\\]+)\\?"/),handlerUrl:pick(html,/handlerUrl:\s*\\?"([^"\\]+)\\?"/),cacheInfoKey:pick(html,/cacheInfoKey:\s*\\?"([^"\\]+)\\?"/)};const H=O+c.handlerUrl,headers={...common,referer:T,cookie,accept:'*/*'};const prep=await fetch(H+'/PrepareDocument',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({cacheInfoKey:c.cacheInfoKey,stateId:c.stateId})});console.log('PREPARE_RESULT',await prep.text());const q=new URLSearchParams({cacheInfoKey:c.cacheInfoKey,stateId:c.stateId});const dl=await fetch(H+'/DownloadDocument?'+q.toString(),{headers});const xpz=Buffer.from(await dl.arrayBuffer()),password=c.cacheInfoKey.split('/')[0].replace(/\.[^.]*$/,'');const parts=decryptZip(xpz,password);const imgs=parts.filter(x=>/^Images\/\d+\.jpg$/i.test(x.name)&&x.data).sort((a,b)=>parseInt(a.name.match(/\d+/)[0])-parseInt(b.name.match(/\d+/)[0]));console.log('DECRYPTED_IMAGES',imgs.map(x=>x.name+':'+x.data.length).join(','));
 let Tesseract;try{Tesseract=require('tesseract.js');}catch{console.log('INSTALLING_TESSERACT_JS');cp.execFileSync('npm',['install','tesseract.js@6','--no-save','--no-audit','--no-fund'],{stdio:'inherit',timeout:180000});Tesseract=require('tesseract.js');}
 const worker=await Tesseract.createWorker('eng',Tesseract.OEM.LSTM_ONLY,{logger:m=>{if(m.status==='recognizing text'&&Math.round(m.progress*100)%25===0)console.log('OCR_PROGRESS',Math.round(m.progress*100));}});await worker.setParameters({preserve_interword_spaces:'1'});const pages=[];for(let i=0;i<imgs.length;i++){const page=i+1;console.log('OCR_PAGE_START',page,imgs[i].name);const r=await worker.recognize(imgs[i].data);const text=(r.data.text||'').trim();const entry={page,image:imgs[i].name,confidence:r.data.confidence,text};pages.push(entry);console.log('OCR_PAGE_RESULT '+page+' '+JSON.stringify(entry));console.log('OCR_PAGE_END',page);}await worker.terminate();result={status:'done',config:c,pageCount:pages.length,pages};console.log('OCR_COMPLETE',pages.length);
}catch(e){result={status:'error',error:String(e&&e.stack||e)};console.error('FATAL',result);}}
main();http.createServer((q,s)=>{s.writeHead(200,{'content-type':'application/json'});s.end(JSON.stringify(result));}).listen(process.env.PORT||10000,'0.0.0.0',()=>console.log('listening'));
